dancingcube/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('dancingcubeapp.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

dancingcubeapp/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path("accounts/register/", views.register, name="register"),
    path('maps/', views.MapListView.as_view(), name='maps'),
    path('maps/create/', views.MapCreateView.as_view(), name='map-create'),
    path('maps/update/<pk>/', views.MapUpdateView.as_view(), name='map-update'),
    path('maps/delete/<pk>/', views.MapDeleteView.as_view(), name='map-delete'),
    path('maps/download/<pk>/', views.MapDownloadView, name='map-download'),
    path('maps/<pk>/', views.MapDetailView.as_view(), name='map-detail'),
    path('search', views.search, name="search"),
    path('like/', views.like_map, name="like_map"),
    path('maps/tags/<slug:name>/', views.TagIndexView.as_view(), name='tagged'),
    path('musicians/', views.musicians, name="musicians"),
    path('leveldesigners/', views.leveldesigners, name="leveldesigners"),
    path('testers/', views.testers, name="testers"),
    path('devs/', views.devs, name="devs"),
    path('trailer/', views.trailer, name="trailer"),
    path('influenceurs/', views.influenceurs, name="influenceurs"),
    path('others/', views.others, name="others"),
    path('follow/', views.follow, name="follow"),
    path('share/', views.share, name="share"),
] + static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

dancingcubeapp/models.py
from django.db import models
from django.urls import reverse
from .validators import validate_file_extension_for_map, validate_file_extension_for_music, validate_file_extension_for_image
from django.contrib.auth.models import User

from taggit.managers import TaggableManager
import os

class Map(models.Model):
    """ Main model of the website. """

    name = models.CharField(max_length=30, default='')
    music = models.FileField(upload_to=f'media{os.sep}musics{os.sep}', validators=[validate_file_extension_for_music])
    EASY = '1'
    MEDIUM = '2'
    HARD = '3'
    diff_rates = [
        (EASY, 'easy'),
        (MEDIUM, 'medium'),
        (HARD, 'hard'),
    ]
    difficulty = models.CharField(
        max_length=1,
        choices=diff_rates,
        default=EASY
        )
    image = models.ImageField(upload_to=f'media{os.sep}images{os.sep}', blank=True, null=True, validators=[validate_file_extension_for_image])
    uploader = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    map = models.FileField(upload_to=f'media{os.sep}maps{os.sep}', validators=[validate_file_extension_for_map]) # Only for the form input to render
    likes = models.ManyToManyField(User, related_name='likes', blank=True)

    tags = TaggableManager() # Init taggit, to tags our maps

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('map-detail', kwargs={'pk': self.pk})

    def total_likes(self):
        """ Return how much likes this map has. """
        return self.likes.count()
    
    def liked_by_user(self, user_id):
        """ Return True if the user with the user_id already liked the map, else False """
        return self.likes.filter(id=user_id).exists()
    
    def name_without_spaces(self):
        """ Return the name attribute but replaced spaces char with underscores (_) """
        return self.name.replace(' ', '_')

class MapFile(models.Model):
    """ Allow to have multiple files in the map """
    file = models.FileField(upload_to=f'media{os.sep}maps{os.sep}', validators=[validate_file_extension_for_map])
    map = models.ForeignKey(Map, on_delete=models.CASCADE)

dancingcubeapp/forms.py
from django.forms import ModelForm
from django import forms
from django.forms import ClearableFileInput
from .models import Map, MapFile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class MapForm(ModelForm):
    class Meta:
        model = Map
        fields = '__all__'

class MapFileForm(ModelForm):
    class Meta:
        model = MapFile
        fields = ['file']
        widget = {
            'file': ClearableFileInput(attrs={'multiple': True}),
        }

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

dancingcubeapp/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic, View
from django.urls import reverse_lazy, reverse
from django.db.models import Q
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, JsonResponse
from django.utils.translation import gettext as _
from django.template.loader import render_to_string
from django.conf import settings

import os
from zipfile import ZipFile
from io import BytesIO
from zipfile import ZipFile

from .models import Map, MapFile
from .forms import MapForm
from .forms import RegisterForm

def register(response):
    """ Register function for signup """
    
    if response.method == "POST":
        form = RegisterForm(response.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(response, user)
            return redirect("index")
    else:
        form = RegisterForm()

    return render(response, "registration/register.html", {"form":form})

def index(request):
    """ Home page """
    context = {}
    return render(request, 'dancingcubeapp/index.html', context)

def musicians(request):
    """ Musician page (url name: musicians) """
    context = {}
    return render(request, 'dancingcubeapp/musician.html', context)

def leveldesigners(request):
    """ Level designers page (url name: leveldesigners) """
    context = {}
    return render(request, 'dancingcubeapp/index.html', context)

def testers(request):
    """ Testers page (url name: testers) """
    context = {}
    return render(request, 'dancingcubeapp/index.html', context)


def devs(request):
    """ Devs page (url name: devs) """
    context = {}
    return render(request, 'dancingcubeapp/index.html', context)

def trailer(request):
    """ Trailer page (url name: trailer) """
    context = {}
    return render(request, 'dancingcubeapp/index.html', context)

def influenceurs(request):
    """ Influenceurs  page (url name: influenceurs) """
    context = {}
    return render(request, 'dancingcubeapp/index.html', context)

def others(request):
    """ Others page (url name: others) """
    context = {}
    return render(request, 'dancingcubeapp/index.html', context)

def follow(request):
    """ Follow page (url name: follow) """
    context = {}
    return render(request, 'dancingcubeapp/index.html', context)

def share(request):
    """ Share page (url name: share) """
    context = {}
    return render(request, 'dancingcubeapp/index.html', context)

def search(request):
    """ When performing a research (Search page) """
    
    query_term = request.GET.get('q') # Getting the query term (Getter arg)
    qs = filter_maps(query_term) # Calling the filter function

    context = {
        'results': qs,
        'query_term': query_term
    }

    return render(request, 'dancingcubeapp/search_result.html', context)

def filter_maps(query_term):
    """ Filtering maps when performing a research base on an arg (query_term).
    Filter based on the name of the map, the name of the music, and the uploader's username.
    """
    
    qs = Map.objects.all() # All maps

    if query_term != '' and query_term is not None:
        qs = qs.filter(
            Q(name__icontains=query_term) |
            Q(music__icontains=query_term) |
            Q(uploader__username__icontains=query_term)
        ).distinct()

    return qs


class MapListView(generic.ListView):
    """ Listing all maps page (url name: maps) """

    model = Map

    def get_queryset(self):
        return Map.objects.all()

class MapDetailView(generic.DetailView):
    """ Specific map page (url name: map-detail) """

    model = Map

    def get_context_data(self, **kwargs):
        
        context = super().get_context_data(**kwargs)
        
        # Adding to context if the current user already liked this specific map
        context['is_liked'] = self.object.liked_by_user(self.request.user.id)

        return context

class MapCreateView(LoginRequiredMixin, generic.edit.CreateView):
    """ Form page, to create a map by a user. (url name: map-create)
    Multiple files upload source: https://stackoverflow.com/q/38257231
    """

    model = Map
    fields = ('name', 'music', 'difficulty', 'image', 'map', 'tags')

    def form_valid(self, form):
        form.instance.uploader = self.request.user
        if self.request.FILES:
            obj = form.save(commit=False)
            obj.save()
            for f in self.request.FILES.getlist('map'):
                if f.size > 1024*1024*2:
                    return redirect("map-create")
                map_file = MapFile(file = f, map = obj)
                map_file.save()

        # Below are 3 attempt to add the difficulty (EASY, MEDIUM or HARD) as a taggit tag.
        # First two attempts creates the tags (in the table *taggit-tag*) but unfortunately does not link the tag with the object (map). 
        # Unfortunately, there is no M2M relationship in the *taggit_taggeditem* table...
        # Fore more informations and how we tried to handle it: https://github.com/HE-Arc/DancingCubeDjango/issues/8

        # difficulties = {"1": "EASY", "2": "MEDIUM", "3": "HARD"} # hard-coded, not great

        # Attempt 1
        """ # saving with commit=False, https://stackoverflow.com/a/51174259/11553000 or the official documentation https://django-taggit.readthedocs.io/en/latest/forms.html
        new_map = form.save(commit=False)
        new_map.uploader =  self.request.user
        new_map.save()
        new_map.tags.add(difficulties[form.cleaned_data["difficulty"]])
        new_map.save() # ?
        form.save_m2m()
        """

        # Attempt 2
        """ # https://stackoverflow.com/a/5361504/11553000
        name = form.cleaned_data['name']
        tags = form.cleaned_data['tags']
        new_map = Map(name=name, uploader=self.request.user)
        new_map.save()
        new_map.tags.add(*tags)
        new_map.tags.add(difficulties[form.cleaned_data["difficulty"]])
        """

        # Attempt 3
        """ # adding by force the tag. Does not work at all.
        #form.cleaned_data["tags"].append(difficulties[form.instance.difficulty]) # add difficulty as tag
        """

        return super(MapCreateView, self).form_valid(form)

    def handle_uploaded_file(f):
        with open('some/file/name.txt', 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)

class MapUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    """ Whenever someones is trying to edit a map. (url name: map-update).
    This operation is only for the owner of the uploader or an admin. Throw a 404 else.
    """

    model = Map
    fields = ('name', 'music', 'difficulty', 'image', 'map', 'tags')

    def get_object(self, queryset=None):
        print("salut1")
        obj = super(MapUpdateView, self).get_object(queryset)
        if obj.uploader == self.request.user or self.request.user.has_perm('dancingcubeapp.map.update'):
            map_files = MapFile.objects.filter(map = obj)
            if map_files.exists():
                map_files.delete()
                obj.save()
                print("salu2t")
            for f in self.request.FILES.getlist('map'):
                print(f)
                mapFile = MapFile(file = f, map = obj)
                mapFile.save()
            return obj
        else:
            # Translators: user updating a map he doesn't own
            raise Http404(_("You don't own this object"))

class MapDeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    """ 'Are you sure you want to delete this map ?' page. (url name: map-delete) """

    login_url = 'login'
    model = Map
    success_url = reverse_lazy('maps')

def MapDownloadView(request, pk):
    """
    Downloading a map: create a zip on the fly.
    Source: https://chase-seibert.github.io/blog/2010/07/23/django-zip-files-create-dynamic-in-memory-archives-with-pythons-zipfile.html .
    Credit to @Ishydo on Github, thanks.
    """

    map = Map.objects.get(pk = pk) # Getting current map

    zip_files_paths = [
        os.path.join(settings.MEDIA_ROOT, str(map.image)).replace('/', os.sep).replace('\\', os.sep), # dirty ?
        os.path.join(settings.MEDIA_ROOT, str(map.music)).replace('/', os.sep).replace('\\', os.sep),
    ]

    # handling multiple files
    map_files = MapFile.objects.filter(map = map)
    for map_f in map_files:
        zip_files_paths.append(os.path.join(settings.MEDIA_ROOT, str(map_f.file)).replace('/', os.sep).replace('\\', os.sep),)

    # In memory zip
    in_memory = BytesIO()
    zip = ZipFile(in_memory, "a")

    # Add files to zip
    for file in zip_files_paths:
        zip.write(file, os.path.basename(file))

    # fix for Linux zip files read in Windows
    for file in zip.filelist:
        file.create_system = 0

    zip.close()

    response = HttpResponse(content_type="application/zip")
    response["Content-Disposition"] = f"attachment; filename=dancingcube_{map.name_without_spaces()}.zip"

    in_memory.seek(0)
    response.write(in_memory.read())

    return response

def like_map(request):
    """ Whenever a user like a map, add a like to it. If already like by this user, dislike it.
    User has to be authentificated to like/dislike.
    """

    map = get_object_or_404(Map, id=request.POST.get('id')) # Get the map
    is_liked = False

    if request.user.is_authenticated:
        if map.likes.filter(id=request.user.id).exists():
            map.likes.remove(request.user) # dislike
            is_liked = False
        else:
            map.likes.add(request.user) # like
            is_liked = True

    context = {
        'map': map,

dancingcubeapp/templates/dancingcubeapp/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  
  {% block script %}{% endblock %}

  <link rel="stylesheet" href="{% static '/css/default.css' %}">

  <title>{% block title %} {% endblock %}</title>
</head>

<body>
  <div class="container">
    
    {% include 'dancingcubeapp/nav.html' %}

    <div class="row justify-content-center">
      <div class="col-12 mt-2">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>
  <script>
    $(document).ready(function() {
      $('.dropdown-toggle').dropdown()
    });
  </script>
</body>

</html>

dancingcubeapp/templates/dancingcubeapp/index.html
{% extends 'dancingcubeapp/base.html' %}

{% load i18n %}

{% block title %}Home{% endblock %}
{% load static %}

{% block content %}
<!--<h2>{% trans "Introduction" %}</h2>
<img src="{% static '/images/logo_graycube.png' %}" alt="">
<p>
  {% trans "This sentence is supposed to be in ENG: Etienne Hüsler et moi-même Alexander Wohlfahrt, sommes deux développeurs fraîchement diplômés d’un Bachelor en développement logiciel, passionnés par l’univers du jeux vidéo. Nous aimons les imaginer, les créer, en parler et y jouer. Nous avons donc profité de notre travail de Bachelor pour nous adonner à notre passion, et c’est ainsi qu’à vue le jour « Dancing Cube »." %}
</p>
</div>

<div>
  <h2>{% trans "What is Dancing Cube ?" %}</h2>
  <p>
    {% trans "This sentence is supposed to be in ENG: Dancing Cube est un jeu vidéo musical original, de rythme et de réflexe, se jouant jusqu’à 4 joueurs et développé avec le moteur de jeu Unity. Les joueurs se retrouvent enfermés dans un cube qui se déforme au rythme de la musique. Le jeu permet aux joueurs de visualiser et de ressentir la musique, tout en essayant de survivre aux changements que celle-ci apporte au cube. Un éditeur et un générateur automatique sont fournis aux joueurs pour qu’ils puissent créer leurs niveaux et les partager." %}
  </p>
</div>-->


<div>
  <div class="text-center my-5">
    <img src="{% static '/images/logo_graycube.png' %}" class="img-fluid" alt="Responsive image">
  </div>
  <div>
    <h2><b>Introduction / Contextualisation</b></h2>

    <p>
      Etienne Hüsler et moi-même Alexander Wohlfahrt, sommes deux développeurs fraîchement diplômés d’un Bachelor en
      développement logiciel, passionnés par l’univers du jeux vidéo. Nous aimons les imaginer, les créer, en parler et
      y
      jouer. Nous avons donc profité de notre travail de Bachelor pour nous adonner à notre passion, et c’est ainsi qu’à
      vue
      le jour « Dancing Cube ».
    </p>

    <p>
      Maintenant que nous possédons les droits sur ce projet, nous souhaitons le poursuivre et sortir une première
      version courant 2020. Nous avons déjà un prototype bien avancé, stable et jouable ! Mais nous travaillons encore
      activement dessus afin de l’améliorer et de proposer la meilleure expérience possible dès la sortie du jeu.
    </p>

    <p>
      Nous avons déjà eu l’occasion de présenter notre jeu dans divers événements en Suisse, comme la GSGS (NIFF
      extended), le Numerik Games Festival, la Zürich Game Show qui est l’un des plus grand festival dans le domaine du
      jeu vidéo en Suisse. Et nous sommes en train de préparer les prochaines conventions.
    </p>

    <p>
      <b>IMPORTANT !</b> Afin de mieux comprendre le projet et le jeu, nous vous invitons à lire la section suivante,
      puis de
      parcourir la section qui suit « Ce que nous cherchons en résumé ».
    </p>
  </div>

</div>
<div>
  <h2><b>Qu’est ce que Dancing Cube ?</b></h2>

  <p>
    Dancing Cube est un jeu vidéo musical original, de rythme et de réflexe, se jouant jusqu’à 4 joueurs et développé
    avec le moteur de jeu Unity. Les joueurs se retrouvent enfermés dans un cube qui se déforme au rythme de la
    musique. Le jeu permet aux joueurs de visualiser et de ressentir la musique, tout en essayant de survivre aux
    changements que celle-ci apporte au cube. Un éditeur et un générateur automatique sont fournis aux joueurs pour
    qu’ils puissent créer leurs niveaux et les partager.
  </p>

  <p>
    Voici un gameplay de l’un de nos niveaux actuels, la musique et le niveau sont temporaires. Cela ne sera pas présent
    lors de la sortie officielle du jeu, nous/vous réaliserons/réaliserez de meilleurs niveaux avec vos musiques !
  </p>

  <iframe src="https://www.youtube.com/embed/seCt8OPy62w" frameborder="0"></iframe>


  <p>
    Voici une interview du projet, qui présente de manière complète tous les aspects de notre jeu (il s’agit là d’une
    ancienne version du projet, mais permet tout de même de comprendre le projet dans son ensemble).
  </p>

  <iframe src="https://www.youtube.com/embed/Pf66BVNhroM" frameborder="0"></iframe>

  <p>
    <b>IMPORTANT !</b> Si vous êtes intéressé par nous aider d’une manière ou d’une autre, veuillez parcourir les types
    de profils que nous recherchons, disponible dans la section suivante. Merci.
  </p>
</div>


<div>
  <h2 class="text-center"><b>Ce que nous cherchons en résumé</b></h2>
  <p>
    Voici tous les profils de personnes que nous recherchons, lisez le petit résumé de chaque bloc et lisez en détails
    les points qui vous intéresse.
  </p>
  <hr>
</div>

<div>
  <div class="row">
    <div class="col-sm-4 col-12">
      <h3><b>Musiciens</b></h3>
      <img src="{% static '/images/musicians.png' %}" class="img-fluid" alt="Responsive image">
      <p>
        Nous recherchons des musiciens amateurs ou non, qui seraient intéressés par nous fournir des musiques ou d’en
        réaliser pour l’occasion.
        (Si vous êtes intéressé cliquez <b><a href="{% url 'musicians' %}">ici</a></b>)
      </p>
    </div>

    <div class="col-sm-4 col-12">
      <h3><b>Créateur de niveau</b></h3>

      <img src="{% static '/images/editor.png' %}" class="img-fluid" alt="Responsive image">
      <p>
        Nous cherchons également des personnes amateurs ou non, pour nous réaliser des niveaux dans notre jeu, basés sur
        les musiques que nous aurons réalisé avec l’aide des musiciens. Un éditeur 3D vous sera fourni afin de les
        créer.
        (Si vous êtes intéressé cliquez ici)
      </p>
    </div>

    <div class="col-sm-4 col-12">
      <h3><b>Testeurs</b></h3>

      <img src="{% static '/images/game.webp' %}" class="img-fluid" alt="Responsive image">
      <p>
        Nous cherchons des testeurs amateurs ou non, afin de tester notre jeu au complet avant sa sortie officielle. Si
        tester
        un jeu vidéo vous a un jour intéressé, ce poste est probableme-ait pour vous.
        (Si vous êtes intéressé cliquez ici)
      </p>
    </div>
  </div>


  <div class="row">
    <div class="col-sm-4 col-12">
      <h3><b>Développeurs</b></h3>

      <img src="{% static '/images/dev.png' %}" class="img-fluid" alt="Responsive image">
      <p>
        Nous cherchons des développeurs expérimenter dans certains domaine bien précis de la création d’un jeu vidéo.
        (Si vous êtes intéressé cliquez ici)
      </p>
    </div>

    <div class="col-sm-4 col-12">
      <h3><b>Trailer</b></h3>

      <img src="{% static '/images/trailer.png' %}" class="img-fluid" alt="Responsive image">
      <p>
        Nous cherchons aussi une personne qui pourrait nous réaliser un trailer pour notre jeu.
        (Si vous êtes intéressé cliquez ici).
      </p>
    </div>


    <div class="col-sm-4 col-12">
      <h3><b>Influenceurs</b></h3>

      <img src="{% static '/images/influencer.jpg' %}" class="img-fluid" alt="Responsive image">
      <p>
        Les influenceurs sont également les bienvenus.
        (Si vous êtes intéressé cliquez ici).
      </p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4 col-12">
      <h3><b>Autres idées</b></h3>

      <img src="{% static '/images/idea.jpg' %}" class="img-fluid" alt="Responsive image">
      <p>
        Si vous pensez pouvoir nous aider d’une autre manière dans un autre domaine, comme le sound design, le design,
        le graphisme (logo, bannière, carte de visite, etc.), la modélisation ou d’autres domaines auquel nous n’avons
        pas pensé, n’hésitez pas à nous contacter.
        (Si vous êtes intéressé cliquez ici)
      </p>
    </div>

    <div class="col-sm-4 col-12">
      <h3><b>Suivre le projet</b></h3>

      <img src="{% static '/images/follow.png' %}" class="img-fluid" alt="Responsive image">
      <p>
        Et finalement, si le projet vous intéresse mais que vous ne voulez ou ne pouvez pas nous aider, vous pouvez
        nous suivre et rester informé ici.
      </p>
    </div>

    <div class="col-sm-4 col-12">
      <h3><b>Partager le projet</b></h3>

      <img src="{% static '/images/reseau.png' %}" class="img-fluid" alt="Responsive image">
      <p>
        Si vous connaissez quelqu’un qui pourrait être intéressé par notre projet ou si vous souhaitez nous aider à
        propager
        la nouvelle sur les réseaux sociaux ou à d’autres endroits, cliquez ici.
      </p>
    </div>
  </div>

  <hr>
</div>

<div>
  <h2><b>Participer à plusieurs postes</b></h2>
  <p>
    Comme les deadlines ne sont pas les mêmes pour chaque poste, vous pouvez tout à fait participer à plusieurs aspects
    du projet. Mettez « Dancing Cube – Poste1, Poste2, PosteX » en sujet de l’email.
    (En remplaçant bien évidement les « Poste1 », « Poste2 » et « PosteX » par le nom des postes auxquels vous souhaitez
    participer, merci).
  </p>
</div>


<div>
  <h2><b>Conclusion</b></h2>
  <p>
    Merci beaucoup d’avoir pris le temps de nous lire 🙂
  </p>

  <p>
    Merci d’avance énormément à tous ceux qui prendront contact avec nous, nous avons hâte de voir ce que nous pouvons
    faire ensemble.
  </p>

  <p>
    Merci également à tous ceux qui prendront le temps de remplir le formulaire ou de nous suivre sur nos réseaux
    sociaux.
  </p>

  <p>
    D’ailleurs, n’hésitez pas à partager ce site à toutes les personnes que vous pensez, qui pourraient nous aider d’une
    manière ou d’une autre dans notre projet.
  </p>

  <p>
    En attendant d’entendre parler de vous, nous vous souhaitons une excellente journée !
  </p>

  <hr>
</div>

<div>
  <h2><b>Contact</b></h2>
  <p>
    Email : <a href="mailto:dancingcubegame@gmail.com">dancingcubegame@gmail.com</a>
  </p>

  <p>
    Téléphone : Si vous souhaitez nous téléphoner, veuillez tout d’abord prendre contact avec nous par e-mail en nous
    indiquant le motif de votre appel. Merci de votre compréhension.
  </p>

</div>



{% endblock content %}

dancingcubeapp/templates/dancingcubeapp/like.html
{{ total_likes }} Like{{ total_likes|pluralize }}
{% if user.is_authenticated %}
    <form action="{% url 'like_map' %}" method="POST">
        {% csrf_token %}
        {% if is_liked %}
            <button type="submit" id="like" name="map_id" value="{{ map.id }}" class="btn btn-danger">Dislike</button>
        {% else %}
            <button type="submit" id="like" name="map_id" value="{{ map.id }}" class="btn btn-success">Like</button>
        {% endif %}
    </form>
{% endif %}

dancingcubeapp/templates/dancingcubeapp/map_confirm_delete.html
{% extends 'dancingcubeapp/base.html' %}

{% block title %} Details | {{map.name}} {% endblock %}

{% block content %}
  <form method="post">{% csrf_token %}
      <p>Are you sure you want to delete "{{ object }}"?</p>
      <input class="btn btn-outline-danger" type="submit" value="Confirm">
  </form>
{% endblock content %}

dancingcubeapp/templates/dancingcubeapp/map_form.html
{% extends 'dancingcubeapp/base.html' %}

{% block title %} List details {% endblock %}
{% load crispy_forms_tags %}

{% block content %}

    {% if map.name %}
      <h1>{{ map.name }}</h1>
    {% else %}
      <h1>New  map</h1>
    {% endif %}
    <script>
      $(document).ready(function(){
        $('#id_map').attr('multiple', true);
      })
    </script>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Save" class="btn btn-success">
    </form>

{% endblock content %}